### ISSUE TITLE
Subscribing to devices.ControlChanges() blocks main thread?

### ISSUE THREAD

**Issue by truoss** [DevDecoder/HIDDevices#14] opened 2024-03-05 23:47 UTC
Hi, 

I´m not sure how to describe my problem in detail, english isn´t my first language.

I have a net6.0 wpf app using prism for DI. 
At the start of my app I call :
`controlChangesSubscribtion = devices.ControlChanges().Subscribe(OnDeviceControlChanged);`

after that, the execution of anything in the app stops for around 3-4 Seconds. Even parallel Tasks that use awaited HttpClients timeout.
I tried putting the devices.ControlChanges().. into a Task but that did not help.

this is an image without and with the line of code:
![image](https://github.com/DevDecoder/HIDDevices/assets/6495430/b917971e-5f33-480f-9c33-f04f72d1246f)

**Comment by thargy** [comment] 2024-03-06 10:24
Hi @truoss,

I'm afraid you have provided far too little information to diagnose your issue accurately.  However, I will give some pointers.

First, I can confirm that this library is tested and working with .NET 6.0 WPF, so it is more likely that this is an issue with how you've coded your app.

The most likely cause is that you are attempting to interact with the UI before it's initialisation, or from a different thread.  This is likely to be occurring in your handler `OnDeviceControlChanged`.

WPF multi-threading is beyond the scope of this library, and I can't cover it in a simple comment.  Also, you should be intimately familiar with [Reactive Extensions](https://reactivex.io/) and how to use them safely within WPF.

 However, there are some things you may wish to research. Try adding an [`ObserveOn(...)`](https://reactivex.io/documentation/operators/observeon.html) before the `Subscribe` to force publications to appear on the main UI thread if the handler is interacting with the UI.  For example, if you were using a framework such as [ReactiveUI](https://www.reactiveui.net/docs/handbook/scheduling) you could use something like the following which shows a `ViewModel` for your main window:

```csharp
    public class MainViewModel : ViewModel
    {
		...
        private ReadOnlyObservableCollection<DeviceViewModel>? _devices;
        public ReadOnlyObservableCollection<DeviceViewModel> Devices =>
            _devices ?? throw new ObjectDisposedException(nameof(MainViewModel));
		...

        public MainViewModel(...)
        {
			...
            var devices = Locator.Current.GetService<Devices>();
            this.WhenActivated(disposables =>
            {
				...
                // Create readonly observable collection of devices.
                devices.Connected(device => device.ControlUsagesAll(GenericDesktopPage.X, GenericDesktopPage.Y))
                    .Transform(device => new DeviceViewModel(deviceSettings.RegisterChild(device.DevicePath.Replace('.', '_')), device))
                    //.SubscribeOn(RxApp.MainThreadScheduler)
                    .ObserveOn(RxApp.MainThreadScheduler)
                    .Bind(out _devices)
                    .Subscribe()
                    .DisposeWith(disposables);
				...
			}
			...
	}
```

As you can see, there is a lot more to this command than the simple one you've shown, this should provide with hints about what you should be thinking about.

`var devices = Locator.Current.GetService<Devices>();`  get our `Devices` singleton from our DI framework (this one is using Splat).

` this.WhenActivated(disposables => ...)` we only want to subscribe to changes whilst the main view is active, so we on subscribe in the `WhenActivated` handler, and we dispose the subscription (see below) when deactivated.  On many apps the main view will be active for as long as the program is running, but this is a good habit to get into to prevent memory leaks.

`devices.Connected(...)` observe device connections.

`device => device.ControlUsagesAll(GenericDesktopPage.X, GenericDesktopPage.Y))` I am only interested in devices that expose and X & Y value (i.e. joysticks).  This will vastly reduce the amount of changes that I am listening to.

`.Transform(device => new DeviceViewModel(...), device))` we're in the WPF MVVM world, so I don't want to just access the device 'Model' directly, so I transform each device into a `ViewModel`.

`//.SubscribeOn(RxApp.MainThreadScheduler)` I don't need to subscribe on the main thread, that part can happen in the background, instead I-

`.ObserveOn(RxApp.MainThreadScheduler)` observe on the main thread - this is important in WPF apps.  This is probably why yours is blocking and timing out, because the underlying UI technology in WPF is effectively single threaded and is prone to deadlocks.

`.Bind(out _devices)` This method comes from [DynamicData](https://github.com/reactivemarbles/DynamicData), which I recommend for creating reactive collections. It allows the WPF UI to bind directly to your raw data. It does a lot of plumbing for you, which is why I don't need a separate handler.  This is associated with the `Devices` property on my view model:

`private ReadOnlyObservableCollection<DeviceViewModel>? _devices;` which I

`.Subscribe()` the actual subscription.

`.DisposeWith(disposables);` is another handy Rx extension method that takes a composite disposable (from the `WhenActivated` parameter) and adds the subscription.  This means the subscription will be correctly disposed when the window is deactivated.

These hints should help you get started researching how to use Rx in WPF, and apply that to my library.  In the meantime, I'm closing this issue as there is no evidence it is related to my library.  If you can confirm it is an issue with my library, please consider creating a minimal example that you are willing to share for diagnosing the issue.  Otherwise, please at least show code samples of the related functionality and state which library version you are using.

**Closed as completed by thargy** 2024-03-06 10:24 UTC
